import type { Category, ChallengeCard, Difficulty, Mode, PromptCard } from "./story-types";

const ALL: readonly Mode[] = ["family", "silly", "fantasy", "cozy-spooky"];
const FAM: readonly Mode[] = ["family"];
const SIL: readonly Mode[] = ["silly"];
const FAN: readonly Mode[] = ["fantasy"];
const SPK: readonly Mode[] = ["cozy-spooky"];
const FAM_SIL: readonly Mode[] = ["family", "silly"];
const FAM_FAN: readonly Mode[] = ["family", "fantasy"];
const FAM_SPK: readonly Mode[] = ["family", "cozy-spooky"];
const SIL_FAN: readonly Mode[] = ["silly", "fantasy"];
const FAN_SPK: readonly Mode[] = ["fantasy", "cozy-spooky"];
const FAM_SIL_FAN: readonly Mode[] = ["family", "silly", "fantasy"];
const FAM_SIL_SPK: readonly Mode[] = ["family", "silly", "cozy-spooky"];

function card(
  id: string,
  text: string,
  modes: readonly Mode[],
  kidFriendly: boolean,
  legendary = false,
): PromptCard {
  return { id, text, modes, kidFriendly, legendary };
}

export const CHARACTERS: PromptCard[] = [
  card("c01", "Tiny dragon", ALL, true),
  card("c02", "Time-traveling grandma", FAM_SIL_FAN, true),
  card("c03", "Very dramatic squirrel", FAM_SIL, true),
  card("c04", "Alien librarian", SIL_FAN, true),
  card("c05", "Knight afraid of horses", FAN, true),
  card("c06", "Retired superhero", FAM_SIL, true),
  card("c07", "Talking sandwich artist", SIL, true),
  card("c08", "Moon gardener", FAM_FAN, true),
  card("c09", "Friendly ghost who forgot how to boo", SPK, true),
  card("c10", "Sleepy vampire who only drinks juice", SPK, true),
  card("c11", "Talking shadow named Bob", FAM_SPK, true),
  card("c12", "Pirate who is terrible at maps", FAM_SIL, true),
  card("c13", "Robot that only speaks in rhymes", FAM_SIL, true),
  card("c14", "Wizard with a leaky hat", FAN, true),
  card("c15", "Detective duck", FAM_SIL, true),
  card("c16", "Princess who collects rocks", FAM_FAN, true),
  card("c17", "Cloud shepherd", FAM_FAN, true),
  card("c18", "Ninja baker", FAM_SIL, true),
  card("c19", "Museum night guard who naps standing up", FAM, true),
  card("c20", "Space mail carrier", FAM_SIL_FAN, true),
  card("c21", "Gnome mayor", FAN, true),
  card("c22", "Haunted teapot", SPK, true),
  card("c23", "Werewolf in fuzzy slippers", SPK, true),
  card("c24", "Unicorn mechanic", FAN, true),
  card("c25", "Grandpa who can talk to raccoons", FAM, true),
  card("c26", "Baby kraken in a teacup", SIL_FAN, true),
  card("c27", "Overly polite skeleton", SPK, true),
  card("c28", "Cat who thinks it is a knight", FAM_FAN, true),
  card("c29", "Inventor of squeaky shoes", SIL, true),
  card("c30", "Lost constellation", FAM_FAN, true),
  card("c31", "Mermaid who hates swimming", FAN, true),
  card("c32", "Broom that wants a vacation", FAN_SPK, true),
  card("c33", "School-bus driver from the year 3000", FAM_SIL, true),
  card("c34", "Moth who loves tiny lamps", FAM_SIL_SPK, true),
  card("c35", "Chef who only cooks clouds", SIL, true),
  card("c36", "Castle gargoyle who tells jokes", SPK, true),
  card("c37", "Frog with a royal appointment", FAN, true),
  card("c38", "Kid with a map that draws itself", FAM, true),
  card("c39", "Owl librarian who stamps too hard", FAM_SPK, true),
  card("c40", "Astronaut who packed the wrong lunch", FAM_SIL, true),
  card("c41", "Sock puppet that became real", SIL, true),
  card("c42", "Forest ranger made of moss", FAN, true),
  card("c43", "Polite mummy wrapped in scarves", SPK, true),
  card("c44", "Clockmaker who is always late", FAM, false),
  card("c45", "Retired dragon accountant", FAN, false),
  card("c46", "Amateur weather wizard", FAN, true),
  card("c47", "Singing cactus", SIL, true),
  card("c48", "Moonlight courier", FAM_FAN, true, true),
  card("c49", "The last marshmallow knight", FAN, true, true),
  card("c50", "Cosmic storyteller in pajamas", ALL, true, true),
  card("c51", "Bat who is scared of the dark", SPK, true),
  card("c52", "Penguin explorer", FAM, true),
  card("c53", "Moonlight janitor of the old manor", SPK, true),
  card("c54", "Pumpkin who wants a library card", SPK, true),
];

export const PLACES: PromptCard[] = [
  card("p01", "Abandoned theme park", FAM_SIL_SPK, true),
  card("p02", "Library that rearranges itself", FAM_FAN, true),
  card("p03", "Moon-side lemonade stand", FAM_SIL, true),
  card("p04", "Castle that sneezes", SPK, true),
  card("p05", "Candy-powered subway", SIL, true),
  card("p06", "Cloud kitchen", FAM_FAN, true),
  card("p07", "Haunted playground that giggles", SPK, true),
  card("p08", "Underwater post office", FAN, true),
  card("p09", "Grandma's attic of leftover magic", FAM_FAN, true),
  card("p10", "Forest of polite mushrooms", FAN, true),
  card("p11", "School that only opens at midnight", FAM_SPK, true),
  card("p12", "Desert of lost socks", SIL, true),
  card("p13", "Floating farmers market", FAM_FAN, true),
  card("p14", "Cozy crypt with extra blankets", SPK, true),
  card("p15", "Starship cafeteria", FAM_SIL_FAN, true),
  card("p16", "Treehouse parliament", FAM, true),
  card("p17", "Clock-tower bakery", FAM_FAN, true),
  card("p18", "Foggy carnival", FAM_SPK, true),
  card("p19", "Village inside a teacup", FAN, true),
  card("p20", "Museum of unfinished inventions", FAM, true),
  card("p21", "Rainbow sewer (it is nicer than it sounds)", SIL, true),
  card("p22", "Witch's laundromat", FAN_SPK, true),
  card("p23", "Mountain that whispers directions", FAN, true),
  card("p24", "Ice-cream observatory", FAM_SIL, true),
  card("p25", "Backyard that grew overnight", FAM, true),
  card("p26", "Ghost train that serves cocoa", SPK, true),
  card("p27", "Bookshop with doors to other Tuesdays", FAM_FAN, true),
  card("p28", "Pirate harbor made of cardboard", SIL, true),
  card("p29", "Glow-worm cave concert hall", FAM_SPK, true),
  card("p30", "Royal stables full of unimpressed goats", FAN, true),
  card("p31", "Rooftop garden on a dragon", FAN, true),
  card("p32", "Sleepy lighthouse", FAM, true),
  card("p33", "Map shop that sells wrong maps on purpose", SIL_FAN, true),
  card("p34", "Pumpkin cathedral", SPK, true),
  card("p35", "Hidden floor of the grocery store", FAM_SIL, true),
  card("p36", "Crystal greenhouse", FAN, true),
  card("p37", "Attic planetarium", FAM, true),
  card("p38", "Haunted hammock shop", SPK, true),
  card("p39", "Bridge made of pancakes", SIL, true),
  card("p40", "Moonlit swimming hole", FAM, true),
  card("p41", "Dungeon of lost board games", FAN, true),
  card("p42", "Neighborhood that swapped all the houses", FAM, false),
  card("p43", "Embassy of talking furniture", SIL, false),
  card("p44", "Orchard that grows midnight fruit", FAN_SPK, true),
  card("p45", "Subway stop that does not exist on weekdays", FAM, false),
  card("p46", "Cloud castle with leaky towers", FAN, true),
  card("p47", "Storybook circus parked on the moon", ALL, true, true),
  card("p48", "The last quiet meadow in space", FAM_FAN, true, true),
  card("p49", "Whispering wardrobe", SPK, true),
  card("p50", "Bubble factory at the edge of town", FAM_SIL, true),
  card("p51", "Sandcastle city at low tide", FAM, true),
  card("p52", "Owl post sorting room", FAN, true),
  card("p53", "Moonlit greenhouse of night flowers", SPK, true),
  card("p54", "Attic full of polite spiders", SPK, true),
];

export const OBJECTS: PromptCard[] = [
  card("o01", "Suspicious sandwich", FAM_SIL, true),
  card("o02", "Map that refuses to stay folded", FAM_FAN, true),
  card("o03", "Talking backpack", FAM_SIL, true),
  card("o04", "Lantern that shows yesterday", FAM_SPK, true),
  card("o05", "Crown made of spoons", SIL_FAN, true),
  card("o06", "Squeaky boots of destiny", FAN, true),
  card("o07", "Jar of leftover thunder", FAN_SPK, true),
  card("o08", "Rubber duck that knows secrets", SIL, true),
  card("o09", "Pocket-sized moon", FAM_FAN, true),
  card("o10", "Haunted harmonica", SPK, true),
  card("o11", "Recipe for invisible soup", SIL, true),
  card("o12", "Key that opens only the wrong doors", FAM_FAN, true),
  card("o13", "Umbrella that creates tiny weather", FAM, true),
  card("o14", "Paintbrush that paints the future", FAM_FAN, true),
  card("o15", "Snack that grants one polite wish", FAM, true),
  card("o16", "Telescope that looks into stories", FAM_FAN, true),
  card("o17", "Gloves that high-five by themselves", SIL, true),
  card("o18", "Clock that runs on giggles", FAM_SIL, true),
  card("o19", "Broom that files complaints", FAN_SPK, true),
  card("o20", "Treasure chest full of extra socks", SIL, true),
  card("o21", "Potion labeled 'probably fine'", FAN, true),
  card("o22", "Mirror that gives pep talks", FAM_SPK, true),
  card("o23", "Compass that points to snacks", FAM_SIL, true),
  card("o24", "Cape that is slightly too dramatic", FAN, true),
  card("o25", "Notebook that writes back", FAM, true),
  card("o26", "Balloon that will not let go", SIL, true),
  card("o27", "Ghost bell that rings softly", SPK, true),
  card("o28", "Seed that grows a tiny house", FAM_FAN, true),
  card("o29", "Mug that refills with courage", FAM, true),
  card("o30", "Violin that summons fireflies", FAM_SPK, true),
  card("o31", "Shield made of toast", SIL_FAN, true),
  card("o32", "Postcard from next week", FAM, false),
  card("o33", "Cursed (friendly) yo-yo", SPK, true),
  card("o34", "Bottle of bottled moonlight", FAN, true),
  card("o35", "Hat that remembers names", FAM, true),
  card("o36", "Puzzle box that tells jokes", SIL, true),
  card("o37", "Sword that is actually a spatula", SIL_FAN, true),
  card("o38", "Camera that photographs feelings", FAM, false),
  card("o39", "Doorknob that hums", SPK, true),
  card("o40", "Kite that tows the whole family", FAM, true),
  card("o41", "Crystal that sneezes glitter", FAN, true),
  card("o42", "Lunchbox of holding", FAM_FAN, true),
  card("o43", "Whistle that calls polite wolves", FAN, true),
  card("o44", "Blanket that is also a map", FAM, true),
  card("o45", "Ring of leftover wishes", FAN, false),
  card("o46", "Story dice that roll themselves", ALL, true, true),
  card("o47", "The original Cosmonaut thermos", FAM, true, true),
  card("o48", "A towel with opinions", SIL, true, true),
  card("o49", "Sticker that grants temporary wings", FAM_FAN, true),
  card("o50", "Bucket of leftover rainbow", SIL, true),
  card("o51", "Candle that smells like adventure", SPK, true),
  card("o52", "Boot with a secret compartment", FAM, true),
  card("o53", "Jar of captured giggles from a graveyard picnic", SPK, true),
  card("o54", "Umbrella that keeps moonlight off", SPK, true),
  card("o55", "Pocket watch that ticks backward at bedtime", FAM_SPK, true),
  card("o56", "Friendly cobweb that points the way", SPK, true),
];

export const PROBLEMS: PromptCard[] = [
  card("x01", "Everything is floating", ALL, true),
  card("x02", "Gravity is taking the day off", FAM_FAN, true),
  card("x03", "The snacks keep escaping", FAM_SIL, true),
  card("x04", "Nobody can remember the plan", FAM, true),
  card("x05", "The doors all lead to the kitchen", SIL, true),
  card("x06", "A polite monster wants to join the team", SPK, true),
  card("x07", "The map is eating itself", FAN, true),
  card("x08", "Time is skipping every other minute", FAM_FAN, false),
  card("x09", "All the colors ran away", FAM, true),
  card("x10", "Someone shrank the hero. A lot.", FAM_SIL, true),
  card("x11", "The moon is stuck in a tree", FAM_FAN, true),
  card("x12", "Echoes are answering before you speak", SPK, true),
  card("x13", "It will not stop raining marshmallows", SIL, true),
  card("x14", "The quest instructions are in crayon", FAN, true),
  card("x15", "A dragon sat on the only bridge", FAN, true),
  card("x16", "Everyone swapped voices", FAM_SIL, true),
  card("x17", "The shadows are playing hide-and-seek", SPK, true),
  card("x18", "The castle is walking away", FAN_SPK, true),
  card("x19", "Shoes have declared independence", SIL, true),
  card("x20", "The library books are arguing", FAM, true),
  card("x21", "Night arrived three hours early", SPK, true),
  card("x22", "A sneeze started a tiny storm", FAM, true),
  card("x23", "The treasure is glued to the ceiling", SIL, true),
  card("x24", "Someone used the magic for chores", FAM_FAN, true),
  card("x25", "The villain booked the same picnic table", FAM, true),
  card("x26", "All clocks think it is bedtime", FAM, true),
  card("x27", "The path keeps looping past a bakery", SIL_FAN, true),
  card("x28", "A ghost lost its rattle", SPK, true),
  card("x29", "The potion was actually soup", FAN, true),
  card("x30", "Birds stole the invitations", FAM, true),
  card("x31", "The floor is lava, but politely", SIL, true),
  card("x32", "A riddle is blocking the bathroom", SIL, true),
  card("x33", "Stars are dripping onto the roof", FAN, true),
  card("x34", "The team has only one matching sock left", FAM, true),
  card("x35", "A friendly curse swapped left and right", SPK, true),
  card("x36", "The king wants a sandwich immediately", FAN, true),
  card("x37", "Music is stuck on the same chorus", FAM, true),
  card("x38", "The boat is a very confident bathtub", SIL, true),
  card("x39", "Fog keeps telling terrible jokes", SPK, true),
  card("x40", "Somebody unplugged the sun", FAM_FAN, true),
  card("x41", "A tiny army of crumbs wants tribute", SIL, true),
  card("x42", "The hero's name is misspelled on the quest", FAN, false),
  card("x43", "Every wish costs one extra chore", FAM, false),
  card("x44", "The night-light went on strike", SPK, true),
  card("x45", "Gravity only works on Tuesdays", FAN, false),
  card("x46", "The story itself is getting impatient", ALL, true, true),
  card("x47", "The cosmos mixed up two Saturdays", FAM, true, true),
  card("x48", "A sneeze opened a secret door", SPK, true, true),
  card("x49", "The picnic basket is walking off", FAM, true),
  card("x50", "Rain is falling upward into a bucket", FAN, true),
  card("x51", "Everyone must hop for one whole scene", SIL, true),
  card("x52", "The lighthouse forgot how to blink", FAM, true),
  card("x53", "The portraits keep swapping hats", SPK, true),
  card("x54", "A friendly howl is stuck on repeat", SPK, true),
];

export const TWISTS: PromptCard[] = [
  card("t01", "The villain is actually helping", ALL, true),
  card("t02", "The sidekick was in charge all along", FAM, true),
  card("t03", "The monster just wants a nap", SPK, true),
  card("t04", "The treasure was a sandwich", SIL, true),
  card("t05", "They were inside a snow globe", FAN, true),
  card("t06", "The map was drawn by a toddler genius", FAM_SIL, true),
  card("t07", "The ghost is the landlord", SPK, true),
  card("t08", "It was a rehearsal for a play", FAM, true),
  card("t09", "The dragon is the missing librarian", FAN, true),
  card("t10", "Everyone is slightly magic except the wizard", FAN, true),
  card("t11", "The curse expires at snack time", FAM_SPK, true),
  card("t12", "The hero and the problem swap places", FAM, false),
  card("t13", "A talking squirrel has the real plan", SIL, true),
  card("t14", "The castle is their old treehouse", FAM_FAN, true),
  card("t15", "The villain's mom packed extra snacks", FAM, true),
  card("t16", "Gravity was a practical joke", SIL, true),
  card("t17", "The object was a friend in disguise", FAM_FAN, true),
  card("t18", "They have been telling the story backward", FAM, false),
  card("t19", "The moon is collecting souvenirs", FAN, true),
  card("t20", "A polite skeleton is the referee", SPK, true),
  card("t21", "The quest was a birthday surprise", FAM, true),
  card("t22", "The sandwich is the narrator", SIL, true),
  card("t23", "Night and day swapped jobs", SPK, true),
  card("t24", "The smallest character is the bravest", FAM, true),
  card("t25", "A prophecy was just a grocery list", FAN, true),
  card("t26", "They have to share the ending", FAM, true),
  card("t27", "The monster's roar is a love song", SPK, true),
  card("t28", "The key opens a picnic instead", FAM, true),
  card("t29", "Time travel was just a very long nap", SIL, true),
  card("t30", "The hero's hat has been steering", FAN, true),
  card("t31", "The shadows vote on the next move", SPK, true),
  card("t32", "The problem solves itself if they dance", SIL, true),
  card("t33", "A lost sock is the chosen one", SIL, true),
  card("t34", "The place is shrinking to pocket size", FAN, true),
  card("t35", "They accidentally adopted the villain", FAM, true),
  card("t36", "The stars want autographs", FAN, true),
  card("t37", "The story needs a new title mid-scene", FAM, false),
  card("t38", "The object grants wishes to everyone except its owner", FAN, false),
  card("t39", "A bedtime story leaked into real life", FAM_SPK, true),
  card("t40", "The final boss is a pop quiz", SIL, true),
  card("t41", "They have to finish in a whisper", SPK, true),
  card("t42", "The whole town was in on it", FAM, true),
  card("t43", "The comet is late on purpose", FAN, true),
  card("t44", "Someone has to hug the problem", FAM, true),
  card("t45", "The twist is that there is extra dessert", FAM_SIL, true),
  card("t46", "The dice have been listening", ALL, true, true),
  card("t47", "The cosmos would like a sequel", FAM, true, true),
  card("t48", "Don't panic — bring a towel", SIL, true, true),
  card("t49", "The ghost was babysitting", SPK, true),
  card("t50", "The horse was the knight the whole time", FAN, true),
  card("t51", "A grandma invented the quest for fun", FAM, true),
  card("t52", "The ending is a dance party", ALL, true),
  card("t53", "The cobwebs were party streamers", SPK, true),
  card("t54", "The haunted house wanted a sleepover", SPK, true),
];

export const CHALLENGES: ChallengeCard[] = [
  { id: "h01", text: "Include a ridiculous sound effect.", modes: ALL, kidFriendly: true },
  { id: "h02", text: "Someone must whisper one sentence.", modes: ALL, kidFriendly: true },
  { id: "h03", text: "Introduce a new sidekick.", modes: ALL, kidFriendly: true },
  { id: "h04", text: "Make something unexpectedly tiny.", modes: ALL, kidFriendly: true },
  { id: "h05", text: "The next sentence must begin with “Unfortunately…”", modes: ALL, kidFriendly: true },
  { id: "h06", text: "Someone has to dramatically gasp.", modes: ALL, kidFriendly: true },
  { id: "h07", text: "Give an object a secret opinion.", modes: ALL, kidFriendly: true },
  { id: "h08", text: "Add a snack to the scene.", modes: FAM_SIL, kidFriendly: true },
  { id: "h09", text: "Describe the weather as if it has feelings.", modes: ALL, kidFriendly: true },
  { id: "h10", text: "Someone must speak in a silly accent for one line.", modes: SIL, kidFriendly: true },
  { id: "h11", text: "A ghost politely knocks first.", modes: SPK, kidFriendly: true },
  { id: "h12", text: "Name a spell after a household chore.", modes: FAN, kidFriendly: true },
  { id: "h13", text: "Make the hero ask for directions.", modes: FAM, kidFriendly: true },
  { id: "h14", text: "The next sentence must include the word “meanwhile.”", modes: ALL, kidFriendly: true },
  { id: "h15", text: "Have two characters high-five for no reason.", modes: FAM_SIL, kidFriendly: true },
  { id: "h16", text: "Turn a problem into a dance.", modes: SIL, kidFriendly: true },
  { id: "h17", text: "Add a talking animal that is not helpful.", modes: FAM_FAN, kidFriendly: true },
  { id: "h18", text: "Someone must clap slowly after a reveal.", modes: ALL, kidFriendly: true },
  { id: "h19", text: "Describe a smell that does not belong.", modes: ALL, kidFriendly: true },
  { id: "h20", text: "Use the object in a way nobody expects.", modes: ALL, kidFriendly: true },
  { id: "h21", text: "A shadow copies the last sentence.", modes: SPK, kidFriendly: true },
  { id: "h22", text: "The next line must be a question.", modes: ALL, kidFriendly: true },
  { id: "h23", text: "Give the place a nickname.", modes: ALL, kidFriendly: true },
  { id: "h24", text: "Someone yells “Plot twist!” then continues normally.", modes: SIL, kidFriendly: true },
  { id: "h25", text: "A quest notice appears on a refrigerator.", modes: FAM, kidFriendly: true },
  { id: "h26", text: "Make the villain trip over nothing.", modes: FAN, kidFriendly: true },
  { id: "h27", text: "Include a countdown from three.", modes: ALL, kidFriendly: true },
  { id: "h28", text: "Someone must hum the next sentence.", modes: FAM_SIL, kidFriendly: true },
  { id: "h29", text: "Reveal that a character has been holding a snack.", modes: FAM, kidFriendly: true },
  { id: "h30", text: "The moon comments on the action.", modes: FAN, kidFriendly: true },
  { id: "h31", text: "Add a rule that lasts only this turn.", modes: ALL, kidFriendly: false },
  { id: "h32", text: "Tell the next beat as a news headline.", modes: FAM, kidFriendly: false },
  { id: "h33", text: "A lantern answers a question.", modes: SPK, kidFriendly: true },
  { id: "h34", text: "Start with “And then, because the dice said so…”", modes: ALL, kidFriendly: true },
  { id: "h35", text: "Make something unexpectedly enormous.", modes: ALL, kidFriendly: true },
  { id: "h36", text: "Pass the phone after a cliffhanger gasp.", modes: ALL, kidFriendly: true },
];

export const DECKS: Record<Category, PromptCard[]> = {
  character: CHARACTERS,
  place: PLACES,
  object: OBJECTS,
  problem: PROBLEMS,
  twist: TWISTS,
};

export const TURN_PROMPTS = [
  "Tell what happens next.",
  "Introduce the object.",
  "Make the problem worse.",
  "Use the wild twist.",
  "Bring the place to life.",
  "Give the character a choice.",
] as const;

export function filterPrompts(
  cards: readonly PromptCard[],
  mode: Mode,
  difficulty: Difficulty,
): PromptCard[] {
  return cards.filter((card) => {
    if (!card.modes.includes(mode)) return false;
    if (difficulty === "kid-friendly" && !card.kidFriendly) return false;
    return true;
  });
}

export function filterChallenges(
  mode: Mode,
  difficulty: Difficulty,
): ChallengeCard[] {
  return CHALLENGES.filter((card) => {
    if (!card.modes.includes(mode)) return false;
    if (difficulty === "kid-friendly" && !card.kidFriendly) return false;
    return true;
  });
}
