import csv

master = "Minimalist 3D voxel style, high-quality matte plastic material, toy-like aesthetic, soft ambient lighting, clean sharp voxel edges, solid white background, high definition, professional game asset."

prompts = [["Player_Forward", f"A single cute orange crab character named Claw’d facing directly forward toward the camera. He has two large claws and four small legs. Isometric front view. {master}"],["Player_Away", f"A single cute orange crab character named Claw’d viewed from behind, facing away from the camera. Orange shell and small back legs visible. Isometric back view. {master}"],["Player_Left", f"A single cute orange crab character named Claw’d facing the left side of the screen in profile. Left claw prominently visible. Isometric left-profile view. {master}"],["Player_Right", f"A single cute orange crab character named Claw’d facing the right side of the screen in profile. Right claw prominently visible. Isometric right-profile view. {master}"],["Car_Left", f"A single small, blocky, retro-style sedan car facing the left side of the screen. Painted vibrant red. No visible windows or wheels, just geometric voxel shapes. Isometric left-profile view. {master}"],["Car_Right", f"A single small, blocky, retro-style sedan car facing the right side of the screen. Painted vibrant red. No visible windows or wheels, just geometric voxel shapes. Isometric right-profile view. {master}"],["Truck_Left", f"A single long, blocky delivery truck facing the left side of the screen. Painted military green with a flat rectangular cargo back. Isometric left-profile view. {master}"],["Truck_Right", f"A single long, blocky delivery truck facing the right side of the screen. Painted military green with a flat rectangular cargo back. Isometric right-profile view. {master}"],["Log", f"A simple, blocky wooden log resting horizontally across the screen. Made of flat brown voxel blocks with subtle wood grain color variations. Isometric 3/4 top-down view. {master}"],["Tile_Grass", f"A single square 3D game tile of grass. Made of varied shades of bright green voxels. Flat top with raised 3D blocky depth. Isometric top-down view. {master}"],["Tile_Road", f"A single square 3D game tile of an asphalt road. Dark grey/blueish voxels with a bright yellow dashed line painted down the middle. Flat top with raised 3D blocky depth. Isometric top-down view. {master}"],["Tile_Water", f"A single square 3D game tile of a river. Made of slightly translucent, vibrant blue voxels with subtle lighter blue highlights for ripples. Flat top with raised 3D blocky depth. Isometric top-down view. {master}"]
]

with open('game_prompts.csv', mode='w', newline='', encoding='utf-8') as file:
    writer = csv.writer(file)
    writer.writerow(["Asset_Name", "Prompt"])
    writer.writerows(prompts)

print("game_prompts.csv has been created successfully!")